CREATE TABLE T_CLYVO_responsavel(
  id_responsavel number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  cpf_responsavel VARCHAR(20) UNIQUE NOT NULL,
  nm_responsavel VARCHAR(20) NOT NULL,
  nr_telefone_responsavel VARCHAR(13) NOT NULL
);

CREATE TABLE T_CLYVO_ANIMAL(
  id_animal number(2) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  rg_animal VARCHAR(20),
  nr_microchip_animal VARCHAR(20),
  nm_animal VARCHAR(20) NOT NULL,
  dt_nascimento_animal DATE NOT NULL,
  peso_animal number(5,2) NOT NULL,
  especie_animal VARCHAR(20) NOT NULL,
  raca_animal VARCHAR(20) NOT NULL,
  id_responsavel number(2) NOT NULL,
  CONSTRAINT fk_an_responsavel FOREIGN KEY (id_responsavel) REFERENCES T_CLYVO_responsavel(id_responsavel)
);


-- Inserindo Responsáveis (3 cadastros)
INSERT INTO T_CLYVO_responsavel (id_responsavel, cpf_responsavel, nm_responsavel, nr_telefone_responsavel)
VALUES (1, '123.456.789-00', 'Maria Silva', '11987654321');

INSERT INTO T_CLYVO_responsavel (id_responsavel, cpf_responsavel, nm_responsavel, nr_telefone_responsavel)
VALUES (2, '987.654.321-00', 'Joao Souza', '11912345678');

INSERT INTO T_CLYVO_responsavel (id_responsavel, cpf_responsavel, nm_responsavel, nr_telefone_responsavel)
VALUES (3, '456.123.789-11', 'Ana Costa', '11998877665');

-- Inserindo Animais (5 cadastros distribuídos entre os responsáveis)
INSERT INTO T_CLYVO_ANIMAL (id_animal, rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (1, 'RG-12345-SP', 'CHIP-9988-BR', 'Rex', TO_DATE('2020-05-10', 'YYYY-MM-DD'), 22.50, 'Cachorro', 'Labrador', 1);

INSERT INTO T_CLYVO_ANIMAL (id_animal, rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (2, 'RG-67890-SP', 'CHIP-7766-BR', 'Mia', TO_DATE('2021-08-22', 'YYYY-MM-DD'), 4.20, 'Gato', 'Siames', 1);

INSERT INTO T_CLYVO_ANIMAL (id_animal, rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (3, 'RG-55443-RJ', 'CHIP-1122-BR', 'Thor', TO_DATE('2019-11-15', 'YYYY-MM-DD'), 31.00, 'Cachorro', 'Pitbull', 2);

INSERT INTO T_CLYVO_ANIMAL (id_animal, rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (4, 'RG-99887-MG', 'CHIP-3344-BR', 'Mel', TO_DATE('2022-01-10', 'YYYY-MM-DD'), 8.50, 'Cachorro', 'Poodle', 2);

INSERT INTO T_CLYVO_ANIMAL (id_animal, rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (5, 'RG-33221-RS', 'CHIP-5566-BR', 'Bolt', TO_DATE('2023-03-05', 'YYYY-MM-DD'), 5.00, 'Gato', 'Persa', 3);

COMMIT;
