-- ===================================================================
-- SCRIPT DE CRIAÇÃO COMPLETO - PROJETO CLYVO
-- ===================================================================

-- Limpeza de tabelas anteriores
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_MEDICAMENTO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_PRESCRICAO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_CONSULTA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_CARTEIRAVACINAL CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_ENDERECO_ANIMAL CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_ANIMAL CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_ENDERECO_RESPONSAVEL CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_RESPONSAVEL CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_VET_CLINICA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_ENDERECO_CLINICA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLINICA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_CLYVO_VET CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_LOGS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END; /

-- 1. T_CLYVO_VET
CREATE TABLE T_CLYVO_VET (
    id_vet NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_vet VARCHAR2(100) NOT NULL,
    cpf_vet VARCHAR2(14) UNIQUE NOT NULL,
    cmrv_vet VARCHAR2(20) UNIQUE NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    senha VARCHAR2(100) NOT NULL
);

-- 2. CLINICA
CREATE TABLE CLINICA (
    id_clinica NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj_clinica VARCHAR2(20) UNIQUE NOT NULL,
    nm_clinica VARCHAR2(100) NOT NULL
);

-- 3. T_CLYVO_ENDERECO_CLINICA
CREATE TABLE T_CLYVO_ENDERECO_CLINICA (
    id_endereco_clinica NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pais VARCHAR2(50) NOT NULL,
    estado VARCHAR2(50) NOT NULL,
    cidade VARCHAR2(100) NOT NULL,
    bairro VARCHAR2(100) NOT NULL,
    logradouro_rua VARCHAR2(150) NOT NULL,
    nr_rua VARCHAR2(15) NOT NULL,
    complemento VARCHAR2(100),
    cep VARCHAR2(9) NOT NULL,
    id_clinica NUMBER(10) NOT NULL,
    CONSTRAINT fk_en_clinica FOREIGN KEY (id_clinica) REFERENCES CLINICA(id_clinica)
);

-- 4. T_CLYVO_VET_CLINICA
CREATE TABLE T_CLYVO_VET_CLINICA (
    id_clinica_vet NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vet NUMBER(10) NOT NULL,
    id_clinica NUMBER(10) NOT NULL,
    CONSTRAINT fk_vet FOREIGN KEY(id_vet) REFERENCES T_CLYVO_VET(id_vet),
    CONSTRAINT fk_clinica FOREIGN KEY(id_clinica) REFERENCES CLINICA(id_clinica)
);

-- 5. T_CLYVO_RESPONSAVEL
CREATE TABLE T_CLYVO_RESPONSAVEL (
    id_responsavel NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf_responsavel VARCHAR2(20) UNIQUE NOT NULL,
    nm_responsavel VARCHAR2(100) NOT NULL,
    nr_telefone_responsavel VARCHAR2(13) NOT NULL
);

-- 6. T_CLYVO_ENDERECO_RESPONSAVEL
CREATE TABLE T_CLYVO_ENDERECO_RESPONSAVEL (
    id_endereco_responsavel NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pais VARCHAR2(50) NOT NULL,
    estado VARCHAR2(50) NOT NULL,
    cidade VARCHAR2(100) NOT NULL,
    bairro VARCHAR2(100) NOT NULL,
    logradouro_rua VARCHAR2(150) NOT NULL,
    nr_rua VARCHAR2(15) NOT NULL,
    complemento VARCHAR2(100),
    cep VARCHAR2(9) NOT NULL,
    id_responsavel NUMBER(10) UNIQUE NOT NULL,
    CONSTRAINT fk_en_responsavel FOREIGN KEY(id_responsavel) REFERENCES T_CLYVO_RESPONSAVEL(id_responsavel)
);

-- 7. T_CLYVO_ANIMAL
CREATE TABLE T_CLYVO_ANIMAL (
    id_animal NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rg_animal VARCHAR2(20),
    nr_microchip_animal VARCHAR2(30),
    nm_animal VARCHAR2(50) NOT NULL,
    dt_nascimento_animal DATE NOT NULL,
    peso_animal NUMBER(5,2) NOT NULL,
    especie_animal VARCHAR2(50) NOT NULL,
    raca_animal VARCHAR2(50) NOT NULL,
    id_responsavel NUMBER(10) NOT NULL,
    CONSTRAINT fk_an_responsavel FOREIGN KEY (id_responsavel) REFERENCES T_CLYVO_RESPONSAVEL(id_responsavel)
);

-- 8. T_CLYVO_ENDERECO_ANIMAL
CREATE TABLE T_CLYVO_ENDERECO_ANIMAL (
    id_endereco_animal NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pais VARCHAR2(50) NOT NULL,
    estado VARCHAR2(50) NOT NULL,
    cidade VARCHAR2(100) NOT NULL,
    bairro VARCHAR2(100) NOT NULL,
    logradouro_rua VARCHAR2(150) NOT NULL,
    nr_rua VARCHAR2(15) NOT NULL,
    complemento VARCHAR2(100),
    cep VARCHAR2(9) NOT NULL,
    id_animal NUMBER(10) UNIQUE NOT NULL,
    CONSTRAINT fk_en_animal FOREIGN KEY(id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

-- 9. T_CLYVO_CARTEIRAVACINAL
CREATE TABLE T_CLYVO_CARTEIRAVACINAL (
    id_carteiravacinal NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_vacina VARCHAR2(100) NOT NULL,
    dt_vacinacao_prevista DATE NOT NULL,
    dt_vacinacao_efetuada DATE,
    st_vacinacao VARCHAR2(30) NOT NULL,
    id_animal NUMBER(10) NOT NULL,
    CONSTRAINT fk_an_carteiravacinal FOREIGN KEY (id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

-- 10. T_CLYVO_CONSULTA
CREATE TABLE T_CLYVO_CONSULTA (
    id_consulta NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    historico_consulta VARCHAR2(1000),
    st_consulta VARCHAR2(30) NOT NULL,
    dt_consulta DATE NOT NULL,
    id_vet NUMBER(10) NOT NULL,
    id_animal NUMBER(10) NOT NULL,
    CONSTRAINT fk_con_vet FOREIGN KEY (id_vet) REFERENCES T_CLYVO_VET(id_vet),
    CONSTRAINT fk_con_animal FOREIGN KEY (id_animal) REFERENCES T_CLYVO_ANIMAL(id_animal)
);

-- 11. T_CLYVO_PRESCRICAO
CREATE TABLE T_CLYVO_PRESCRICAO (
    id_prescricao NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_emissao DATE NOT NULL,
    dt_expiracao DATE NOT NULL,
    observacoes_gerais VARCHAR2(500),
    id_consulta NUMBER(10) UNIQUE NOT NULL,
    CONSTRAINT fk_prescricao FOREIGN KEY (id_consulta) REFERENCES T_CLYVO_CONSULTA(id_consulta)
);

-- 12. T_CLYVO_MEDICAMENTO
CREATE TABLE T_CLYVO_MEDICAMENTO (
    id_medicamento NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_medicamento VARCHAR2(100) NOT NULL,
    dosagem_medicamento VARCHAR2(50) NOT NULL,
    frequencia VARCHAR2(50) NOT NULL,
    qtd_dias NUMBER(5) NOT NULL,
    id_prescricao NUMBER(10) NOT NULL,
    CONSTRAINT fk_med_prescicao FOREIGN KEY (id_prescricao) REFERENCES T_CLYVO_PRESCRICAO(id_prescricao)
);

-- 13. T_LOGS
CREATE TABLE T_LOGS (
    id_log NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_procedure VARCHAR2(100) NOT NULL,
    dt_log TIMESTAMP,
    tipo_log VARCHAR2(20),
    cod_log NUMBER(10),
    desc_log CLOB,
    id_vet NUMBER(10),
    CONSTRAINT fk_log_vet FOREIGN KEY (id_vet) REFERENCES T_CLYVO_VET(id_vet)
);

-- Inserções Iniciais
INSERT INTO T_CLYVO_VET (nm_vet, cpf_vet, cmrv_vet, email, senha) VALUES ('Dr. Carlos Silva', '12345678901', 'CRMV-SP12345', 'carlos@email.com', 'senha123');
INSERT INTO CLINICA (cnpj_clinica, nm_clinica) VALUES ('12345678000199', 'Clínica Clyvo Pet');
-- Inserindo Responsáveis (3 cadastros)
INSERT INTO T_CLYVO_responsavel (id_responsavel, cpf_responsavel, nm_responsavel, nr_telefone_responsavel)
VALUES (1, '123.456.789-00', 'Maria Silva', '11987654321');

INSERT INTO T_CLYVO_responsavel (id_responsavel, cpf_responsavel, nm_responsavel, nr_telefone_responsavel)
VALUES (2, '987.654.321-00', 'Joao Souza', '11912345678');

INSERT INTO T_CLYVO_responsavel (id_responsavel, cpf_responsavel, nm_responsavel, nr_telefone_responsavel)
VALUES (3, '456.123.789-11', 'Ana Costa', '11998877665');

-- Inserindo Animais (5 cadastros distribuídos entre os responsáveis)
INSERT INTO T_CLYVO_ANIMAL (id_animal, rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (1, 'RG-12345-SP', 'CHIP-9988-BR', 'Rex', TO_DATE('2020-05-10', 'YYYY-MM-DD'), 22.50, 'Cachorro', 'Labrador', 1);

INSERT INTO T_CLYVO_ANIMAL (id_animal, rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (2, 'RG-67890-SP', 'CHIP-7766-BR', 'Mia', TO_DATE('2021-08-22', 'YYYY-MM-DD'), 4.20, 'Gato', 'Siames', 1);

INSERT INTO T_CLYVO_ANIMAL (id_animal, rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (3, 'RG-55443-RJ', 'CHIP-1122-BR', 'Thor', TO_DATE('2019-11-15', 'YYYY-MM-DD'), 31.00, 'Cachorro', 'Pitbull', 2);

INSERT INTO T_CLYVO_ANIMAL (id_animal, rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (4, 'RG-99887-MG', 'CHIP-3344-BR', 'Mel', TO_DATE('2022-01-10', 'YYYY-MM-DD'), 8.50, 'Cachorro', 'Poodle', 2);

INSERT INTO T_CLYVO_ANIMAL (id_animal, rg_animal, nr_microchip_animal, nm_animal, dt_nascimento_animal, peso_animal, especie_animal, raca_animal, id_responsavel)
VALUES (5, 'RG-33221-RS', 'CHIP-5566-BR', 'Bolt', TO_DATE('2023-03-05', 'YYYY-MM-DD'), 5.00, 'Gato', 'Persa', 3);


COMMIT;








